import "./globals.css";
import Header from "./Header";
import { Saira } from "next/font/google";

const saira = Saira({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // ihtiyacına göre seç
  variable: "--font-saira",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${saira.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
